// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const completeTask = `-- name: CompleteTask :one
INSERT INTO task_completions (id, created_at, updated_at, user_id, task_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1, -- User ID
    $2  -- Task ID
)
ON CONFLICT (user_id, task_id) DO NOTHING
RETURNING id, created_at, updated_at, user_id, task_id
`

type CompleteTaskParams struct {
	UserID uuid.UUID `json:"user_id"`
	TaskID uuid.UUID `json:"task_id"`
}

// If they already finished it, do nothing (don't crash)
func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (TaskCompletion, error) {
	row := q.db.QueryRowContext(ctx, completeTask, arg.UserID, arg.TaskID)
	var i TaskCompletion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.TaskID,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (id, created_at, updated_at, title, description)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, title, description
`

type CreateCourseParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse, arg.Title, arg.Description)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (id, created_at, updated_at, course_id, title, content, "position")
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, course_id, title, content, position
`

type CreateLessonParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Title    string    `json:"title"`
	Content  string    `json:"content"`
	Position int32     `json:"position"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, createLesson,
		arg.CourseID,
		arg.Title,
		arg.Content,
		arg.Position,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseID,
		&i.Title,
		&i.Content,
		&i.Position,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, created_at, updated_at, lesson_id, description)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, lesson_id, description
`

type CreateTaskParams struct {
	LessonID    uuid.UUID `json:"lesson_id"`
	Description string    `json:"description"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.LessonID, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LessonID,
		&i.Description,
	)
	return i, err
}

const createTaskStep = `-- name: CreateTaskStep :one
INSERT INTO task_steps (id, created_at, updated_at, task_id, position, command, expected_output)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, task_id, position, command, expected_output, created_at, updated_at
`

type CreateTaskStepParams struct {
	TaskID         uuid.UUID `json:"task_id"`
	Position       int32     `json:"position"`
	Command        string    `json:"command"`
	ExpectedOutput string    `json:"expected_output"`
}

func (q *Queries) CreateTaskStep(ctx context.Context, arg CreateTaskStepParams) (TaskStep, error) {
	row := q.db.QueryRowContext(ctx, createTaskStep,
		arg.TaskID,
		arg.Position,
		arg.Command,
		arg.ExpectedOutput,
	)
	var i TaskStep
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Position,
		&i.Command,
		&i.ExpectedOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLesson, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getCourse = `-- name: GetCourse :one
SELECT id, created_at, updated_at, title, description FROM courses WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT id, created_at, updated_at, title, description FROM courses
ORDER BY created_at DESC
`

func (q *Queries) GetCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, getCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsByCourseID = `-- name: GetLessonsByCourseID :many
SELECT id, created_at, updated_at, course_id, title, content, position FROM lessons 
WHERE course_id = $1 
ORDER BY "position" ASC
`

func (q *Queries) GetLessonsByCourseID(ctx context.Context, courseID uuid.UUID) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseID,
			&i.Title,
			&i.Content,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStepsByTaskID = `-- name: GetStepsByTaskID :many
SELECT id, task_id, position, command, expected_output, created_at, updated_at FROM task_steps 
WHERE task_id = $1 
ORDER BY position ASC
`

func (q *Queries) GetStepsByTaskID(ctx context.Context, taskID uuid.UUID) ([]TaskStep, error) {
	rows, err := q.db.QueryContext(ctx, getStepsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskStep
	for rows.Next() {
		var i TaskStep
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Position,
			&i.Command,
			&i.ExpectedOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByLessonID = `-- name: GetTaskByLessonID :one
SELECT id, created_at, updated_at, lesson_id, description FROM tasks WHERE lesson_id = $1
`

func (q *Queries) GetTaskByLessonID(ctx context.Context, lessonID uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByLessonID, lessonID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LessonID,
		&i.Description,
	)
	return i, err
}
